#!/bin/bash

echo "🌐 THINK41 E-COMMERCE API LOCATIONS"
echo "===================================="
echo ""
echo "📡 Server Base URL: http://localhost:3000"
echo "🔗 API Base URL: http://localhost:3000/api"
echo ""
echo "📍 AVAILABLE API ENDPOINTS:"
echo "----------------------------"
echo ""
echo "1️⃣  GET /api/products"
echo "    📍 http://localhost:3000/api/products"
echo "    📋 List all products (with pagination)"
echo "    📝 Query params: ?page=1&limit=20"
echo ""
echo "2️⃣  GET /api/products/:id"
echo "    📍 http://localhost:3000/api/products/1"
echo "    📋 Get specific product by ID"
echo "    📝 Replace ':id' with actual product ID"
echo ""
echo "3️⃣  GET /api/products/search"
echo "    📍 http://localhost:3000/api/products/search?q=laptop"
echo "    📋 Search products by name, brand, category"
echo "    📝 Required query param: ?q=searchterm"
echo ""
echo "4️⃣  GET /api/departments"
echo "    📍 http://localhost:3000/api/departments"
echo "    📋 List all available departments"
echo "    📝 No parameters required"
echo ""
echo "5️⃣  GET /api/products/department/:dept"
echo "    📍 http://localhost:3000/api/products/department/Electronics"
echo "    📋 Filter products by department"
echo "    📝 Replace ':dept' with department name"
echo ""
echo "6️⃣  GET /api"
echo "    📍 http://localhost:3000/api"
echo "    📋 API documentation endpoint"
echo "    📝 Shows all available endpoints"
echo ""
echo "7️⃣  GET /health"
echo "    📍 http://localhost:3000/health"
echo "    📋 Health check - server and database status"
echo "    📝 Returns server health information"
echo ""
echo "🧪 QUICK TEST COMMANDS:"
echo "----------------------"
echo ""
echo "# Test in browser - just copy these URLs:"
echo "http://localhost:3000/api/products"
echo "http://localhost:3000/api/products/1"
echo "http://localhost:3000/api/departments"
echo "http://localhost:3000/api/products/search?q=laptop"
echo "http://localhost:3000/health"
echo ""
echo "# Test with cURL commands:"
echo "curl http://localhost:3000/api/products"
echo "curl http://localhost:3000/api/products/1"
echo "curl http://localhost:3000/api/departments"
echo "curl \"http://localhost:3000/api/products/search?q=laptop\""
echo ""
echo "🚀 TO START THE API SERVER:"
echo "---------------------------"
echo "1. Load data: node load_csv_data.js"
echo "2. Start server: node api_server.js"
echo "3. Test API: node test_api.js"
echo ""
echo "📊 SERVER STATUS CHECK:"
echo "----------------------"

# Check if server is running
if curl -s http://localhost:3000/health >/dev/null 2>&1; then
    echo "✅ API Server is RUNNING at http://localhost:3000"
    echo "🎯 Ready to accept requests!"
else
    echo "❌ API Server is NOT RUNNING"
    echo "💡 Start with: node api_server.js"
fi

echo ""
echo "📚 For complete documentation, see: API_DOCUMENTATION.md"
echo "====================================="
